### ISSUE TITLE
start_date_report.py can pass the Qwiklabs Assessment but not really working

### ISSUE THREAD

**Issue by EthanKeng** [kumbasar/IT-Automation-with-Python#1]
Does it work on your side? No error no output on my side. With empty object.

![image](https://user-images.githubusercontent.com/36765774/166406157-35f1b4fd-ea28-47af-81fd-76b930788758.png)
 
![image](https://user-images.githubusercontent.com/36765774/166406203-180e7540-bc92-4ce8-9a8d-30409de31a0b.png)

https://github.com/kumbasar/IT-Automation-with-Python/blob/main/Start-Date-Report/start_date_report.py#L1

**Comment by kumbasar** [comment]
👋 @EthanKeng , please check your input date.

**Comment by EthanKeng** [comment]
Hi @kumbasar ,
I tried several input date and all failed. Could you let me know your succeeded case? What date did you input?

**Comment by kumbasar** [comment]
It seems that the [csv](https://storage.googleapis.com/gwg-hol-assets/gic215/employees-with-date.csv) file was removed:

`SuchBucketThe specified bucket does not exist.`

Could you please provide me the new URL?
